
name: humpack
long_name: HumPack

version: 0.1.1

url: 'https://github.com/felixludos/HumPack'

description: 'Human Readable Object Serialization and more'

author: Felix Leeb
author_email: 'felixludos.info@gmail.com'

license: GPL3

readme: 'README.rst'

packages: ['humpack']

install_requires:
  - wrapt
  - cryptography
